[project]
name = "gibss-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gibss-mono",
    "ipython>=9.13.0",
    "jax>=0.10.0",
    "marimo>=0.23.5",
    "matplotlib>=3.10.9",
    "nicegui>=3.13.0",
    "numpy>=2.4.4",
    "openai>=2.53.0",
    "polars>=1.40.1",
    "pydantic-ai-slim>=2.24.0",
    "pypdfium2>=5.9.0",
    "snakemake>=9.20.0",
    "snakemake-executor-plugin-cluster-generic>=1.0.9",
]

[tool.uv.sources]
gibss-mono = { git = "https://github.com/karltayeb/gibss-mono", rev = "6657979" }

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter-client>=8.9.1",
    "mcp>=1",
    "nbclient>=0.11.0",
    "pydantic>=2",
    "pytest>=9.0.3",
    "python-lsp-ruff>=2.3.1",
    "python-lsp-server>=1.15.0",
    "websockets>=16.0",
]
